### ISSUE TITLE
Missing License file

### ISSUE THREAD

**Issue by hannesgassert** [republik/plattform#103]
Hi there :)

The old repo used to have a license file, https://github.com/orbiting/backends/blob/master/LICENSE, specifying the code to be released under AGPL. This repo doesn't have that file anymore. Is the code still under AGPL, or did the licensing change?

Cheers,
H

**Comment by tpreusse** [comment]
Hello Hannes 👋 

We haven't unified the licencing since merging our apps into a mono repo. I've added a note about the used licenses — BSD-3-Clause for frontend code and AGPL-3.0 for backend code to the readme

**Comment by tpreusse** [comment]
Also happy to discuss specific licensing requirements over a beer. Used to be a BSD-3-Clause fan but after reading Republik for over 4 years I'm starting to lean towards AGPL 😅
