### ISSUE TITLE
HTML-Tags: leere Tags vermeiden, semantisch richtige Tags setzen

### ISSUE THREAD

**Issue by fuenkchen** [republik/plattform#134]
- [x] Startseite: die Sätze "Das digitale Magazin für Politik, Wirtschaft, Gesellschaft und Kultur. Finanziert von seinen Leserinnen." sind als H2 ausgezeichnet, obwohl es sich eher um einen Paragraphen handelt.
- [x] Startseite: an verschiedenen Stellen gibt es leere Paragraphen (leere Tags vermeiden) -> eigentlich, wenn kein format in der kachel, p -> leeres link
- [x] Feed: leere p-Tags vorhanden, falls bei einem Artikel kein Leadtext vorhanden ist => sollte in dem Fall keine leeren Tags geben
- [x] Artikelebene: vor dem Leadtext gibt es ein leeres h2-Tag (sollte vermieden werden), z.B. https://www.republik.ch/2021/05/28/das-verlorene-jahrzehnt-wie-die-schweizer-klimapolitik-durchstartete-und-abstuerzte 

Details unter Issues 30 - 33 im Accessibility Bericht

**Comment by annatraussnig** [comment]
went through our current landing page – didn't find the empty p tags though…
