### ISSUE TITLE
Dialog/Beiträge: Verbessern des aktuell gewählten Sortier-Indikators

### ISSUE THREAD

**Issue by MorgeMoensch** [republik/plattform#183]
Ich finde es ziemlich schwierig zu erkennen, welche Sortierung ich im Dialog ausgewählt habe:

![grafik](https://user-images.githubusercontent.com/62468040/185743678-bae7b3e2-47bd-4eca-9b19-8db69ee9f234.png)

Die visuelle Hervorhebung der aktuellen Auswahl sollte verbessert werden. Zum Beispiel durchs Unterstreichen (wobei die Funtkionalität dann wegen der Links, die auch unterstrichen werden, nicht einheitlich ist) oder durchs Verwenden von Button-Stylen (ähnlich wie der für 'Neuer Beitrag', wenn während dem Lesen ein neuer Beitrag geschrieben wurde).

**Comment by trm217** [comment]
Hi MorgeMonesch, merci für den Input.
Wir haben das Styling angepasst, sodass die aktive Sortierung fortan zusätzlich zur breiteren Schrift noch unterstrichen ist.

**Comment by MorgeMoensch** [comment]
Super, vielen Dank fürs Umsetzen!
