### ISSUE TITLE
Erstellung eines A5 PDFs: "Invalid width"

### ISSUE THREAD

**Issue by ValValetl** [republik/plattform#237]
### Bug Description

Es erscheint die Error Meldung "Invalid width" im Browser wenn man auf den Button A5 PDF generieren klickt.
![grafik](https://user-images.githubusercontent.com/74460707/195861882-9bbe4336-2708-4f17-a8b5-9dfdc8850338.png)

### Expected Behaviour

Erwartetes Verhalten wäre die Anzeige des Artikels als PDF.

### Steps to reproduce

1. https://www.republik.ch/2022/10/06/einer-von-uns
2. PDF Button
3. A5 auswählen (egal ob mit oder ohne bild)
4. Öffnen

### Environment

Firefox

### Version

105.0.3

**Comment by ovbm** [comment]
Vielen Dank für den Report. Wir arbeiten an einer Lösung.

**Comment by patrickvenetz** [comment]
Asset server passed size parameter to PDF server, then to "itself" (`returnImage`) but doing nothing with it.

https://github.com/republik/plattform/pull/225 introduced `size` as a dimesions parameter string, which works for images (800x600), but not so much with PDFs (A5).

**Comment by patrickvenetz** [comment]
@ValValetl Merci fürs Melden und den guten Bug Report. In den nächstn Stunden müsstest du wieder A5-PDFs generieren können.

**Comment by patrickvenetz** [comment]
(Und Gottseidank wars mit «Beta» angeschrieben 😉)
