### ISSUE TITLE
Bug: Quote is not distinguishable in Comment Preview

### ISSUE THREAD

**Issue by MorgeMoensch** [republik/plattform#320]
### Bug Description

When writing a comment with a quote, the quote-styling is not visible in the preview.

Tried with this text:

Ein normaler Text.

> Das ist ein Zitat

### Expected Behaviour

The quote is distinguished similarely as it will be when the comment has been published. I see, that it probably needs a different shade of gray, since the input-text has already a background. But currently it is like this, which is a bit misleading:

![grafik](https://user-images.githubusercontent.com/62468040/210067004-5cd7bba4-b60f-4179-8023-d8f5829e1166.png)

![grafik](https://user-images.githubusercontent.com/62468040/210067035-49b166f1-93f0-467a-9771-af5bab993aba.png)

### Steps to reproduce

Write a comment containing a Quote and click 'Preview'

### Environment

Firefox

**Comment by trm217** [comment]
There's a new Comment-Editor on the horizon, this issue will be gone, once that's released 👍🏻
