### ISSUE TITLE
articles lack clickable dark/bright reading mode switch anywhere on page

### ISSUE THREAD

**Issue by D4n2021** [republik/plattform#461]
### Bug Description

Currently, articles are entirely black (dark mode) when Windows is set to dark and browser-mode is set to automatic. All modern websites nowadays have a bright/dark-switch added, to let users choose which websites they want to read in bright mode (due to the dark mode being **_super_** dark, like republik currently) and which websites they want to read in dark mode (if a website has way too many white areas that are eye-straining.)

### Expected Behaviour

Expected to find a clickable-switch _**anywhere**_ on the article page to give us (loyal) visitors the best possible reading experience and incentive to support republik's offer at https://www.republik.ch/angebote?package=ABO for example :)

### Steps to reproduce

On Windows 10 22H2, set colors to "dark", in webbrowser "website appearance" to "automatic" and visit one of the very basic simple Republik-articles that are presented in a new-tab page by Firefox Pocket, like this very interesting one about anger: https://www.republik.ch/2023/04/24/wut-ist-weiblich?utm_source=pocket-newtab-global-de-DE

### Environment

Firefox

### Version

112.0.2

**Comment by trm217** [comment]
Hi D4n2021, if I understand you correctly you wish to be able to change the color scheme?
If so this is possible, but the toggle is hidden inside a navigation overlay:

![CleanShot 2023-08-10 at 14 22 03@2x](https://github.com/republik/plattform/assets/30313631/ac582c29-bca3-4096-90ec-2184471a1fe7)
Once the overlay is opened
![CleanShot 2023-08-10 at 14 22 20@2x](https://github.com/republik/plattform/assets/30313631/9b1c3320-7d2f-433e-a027-b8d094c235af)

If that's not what you meant, could you elaborate further?

**Comment by trm217** [comment]
We will rework the overlays sometime in the future.
As of now however, I can't say when that will be the case. 
We will keep your feedback in mind 👍
