### ISSUE TITLE
Tag in reply comment preview

### ISSUE THREAD

**Issue by patrickvenetz** [republik/plattform#6]
When I reply to a tagged comment while a specific tag-tab is selected, tag is submitted.

I expect my reply to be without a tag.

<img width="727" alt="Bildschirmfoto 2022-01-31 um 11 53 49" src="https://user-images.githubusercontent.com/331800/151781477-981c1673-751b-46e2-8159-ce86a4829360.png">

[Sample comment on republik.ch](https://www.republik.ch/dialog?t=general&focus=f2e1924d-a6db-411e-a575-e96c8a2eb13d)

**Comment by trm217** [comment]
Couldn't reproduce the issue

**Comment by patrickvenetz** [comment]
Unable to reproduce either.

However, preview of a reply to a (root) comment shows tag (albeit not submitting it afterwards). 

<img width="769" alt="Bildschirmfoto 2022-02-03 um 13 52 15" src="https://user-images.githubusercontent.com/331800/152348150-86a2b780-50e2-466c-8fa9-3a77d71e90b4.png">
