### ISSUE TITLE
Section titles contrast low in dark mode

### ISSUE THREAD

**Issue by patrickvenetz** [republik/plattform#7]
I can't see some section titles on notifcation settings page while in dark mode.

I expect section titles to be visible.

<img width="647" alt="Bildschirmfoto 2022-01-31 um 11 58 41" src="https://user-images.githubusercontent.com/331800/151782145-222fcb8b-3a42-4dc4-a8f9-62b5a8011679.png">

**Steps to Reproduce**

- Login as member, make sure to run in dark mode
- Open [notification settings page](https://www.republik.ch/konto/benachrichtigungen)

**Comment by trm217** [comment]
The color values for the heading are provided by the API (as seen in the screenshot below).
The will have to be adapted if we want it to work in both color-modes

<img width="428" alt="image" src="https://user-images.githubusercontent.com/30313631/152318121-63b35a99-5acb-42ee-941b-4d98279f0bfe.png">
