### ISSUE TITLE
Fade-out ramp visible on focused comment

### ISSUE THREAD

**Issue by patrickvenetz** [republik/plattform#9]
I can see fade-out ramp when opening a focused comment.

I expect fade-out ramp to blend in to focus color to keep appearance of fading text.

<img width="677" alt="Bildschirmfoto 2022-01-27 um 13 11 24" src="https://user-images.githubusercontent.com/331800/151783449-322f9cba-674c-4a5a-a799-95a5143bb115.png">

<img width="646" alt="Bildschirmfoto 2022-01-31 um 12 05 03" src="https://user-images.githubusercontent.com/331800/151783446-0b88bafd-0007-4789-b3c3-c6dc14c144c5.png">

[Sample focused comment on republik.ch](https://www.republik.ch/2021/10/12/fuer-mitglieder-und-abonnentinnen-diskutieren-sie-mit/diskussion?focus=08123aee-528f-424b-86f6-b864e62b6442)

**Comment by ovbm** [comment]
@trm217 I think we had a solution for this prior to the refactor. Not 100% sure though...

**Comment by trm217** [comment]
Fairly certain that the default behavior was for a collapsed comment to be expanded when focused.
I'll fix it in a sec
